behaviors:
  FlappyBall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4096            # INCREASED: Larger replay buffer
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5                 # INCREASED: More training iterations per batch
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256            # INCREASED: More neurons
      num_layers: 3                # INCREASED: Deeper network
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 300000
    time_horizon: 64
    summary_freq: 10000
